openapi: 3.0.0
servers:
  - url: http://wso2-mi-service:8290
info:
  description: 'API MI for IFS Monday'
  version: 1.0.0
  title: Swagger IFS Monday
  contact:
    email: phuongnguyen@tdt.asia
x-wso2-basePath: ''
x-wso2-production-endpoints:
  urls:
    - http://wso2-mi-service:8290
x-wso2-cors:
  accessControlAllowOrigins:
    - '*'
  accessControlAllowHeaders:
    - Authorization
    - Content-Type
  accessControlAllowMethods:
    - GET
    - PUT
    - POST
    - OPTIONS
    - PATCH
  accessControlAllowCredentials: true
  
x-wso2-disable-security: true

paths:
  /dnb/due-diligence-check:
    post:
      tags:
        - dnb-check-monitoring
      operationId: dueDiligenceCheckDNB
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BaseObject'
      parameters:
        - name: dnb-url
          in: header
          required: true
          schema:
            type: string
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: string

  /aml/worldcheck:
    post:
      tags:
        - worldCheck-monitoring
      operationId: dueDiligenceWorldCheck
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BaseObject'
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: string

  /mlcb/getmlcbalq:
    post:
      tags:
        - worldCheck-monitoring
      operationId: mlcbGetMlcbalq
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BaseObject'
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: string

  /mlcb/getmlcbr:
    post:
      tags:
        - worldCheck-monitoring
      operationId: mlcbGetMlcbr
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BaseObject'
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: string

  /mlcb/aprvrjcapp:
    post:
      tags:
        - worldCheck-monitoring
      operationId: mlcbAprvrjcapp
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BaseObject'
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: string

  /mlcb/loanupload:
    post:
      tags:
        - worldCheck-monitoring
      operationId: mlcbLoanUpload
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BaseObject'
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: string

  /mlcb/loantotpay:
    post:
      tags:
        - worldCheck-monitoring
      operationId: mlcbLoanTotPay
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BaseObject'
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: string

  /mlcb/loanpaymnt:
    post:
      tags:
        - worldCheck-monitoring
      operationId: mlcbLoanPaymnt
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BaseObject'
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    BaseObject:
      type: object
