openapi: 3.0.0
servers:
  - url: http://blacklist.monday.svc.cluster.local
info:
  description: 'API Blacklist for IFS Monday'
  version: 1.0.1
  title: Swagger Blacklist IFS Monday
  contact:
    email: phuongnguyen@tdt.asia
x-wso2-basePath: '/blacklist'
x-wso2-production-endpoints:
  urls:
    - http://blacklist.monday.svc.cluster.local
x-wso2-cors:
  accessControlAllowOrigins:
    - '*'
  accessControlAllowHeaders:
    - Authorization
    - Content-Type
  accessControlAllowMethods:
    - GET
    - PUT
    - POST
    - OPTIONS
    - PATCH
  accessControlAllowCredentials: true
  
x-wso2-disable-security: true

paths:
  /v1/global/aml/blacklist:
    get:
      tags:
        - blacklist
      operationId: getBlacklist
      parameters:
        - name: nric
          in: query
          description: Client's NRIC
          required: false
          schema:
            type: string
        - name: clientName
          in: query
          description: Full or partial name of the client
          required: false
          schema:
            type: string
        - name: threshold
          in: query
          description: Similarity threshold for fuzzy matching (0.0 - 1.0)
          required: false
          schema:
            type: number
            format: double
            default: 0.5
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ObjectDTO'
components:
  schemas:
    ObjectDTO:
      type: object
